added some tests
had to change all "10 Steps" to "10Steps" because i can't solve this:
org.json.JSONException: Unterminated object at character 40 of {id:Course1,name:Spring,description:10 Steps}